#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9

# Reset padding untuk monitor HDMI-0 karena tidak ada Polybar di sana
bspc monitor HDMI-0 -M 0
bspc config -m DP-0 top_padding 0
bspc config -m DP-0 bottom_padding 0
bspc config -m HDMI-0 top_padding 0
bspc config -m HDMI-0 bottom_padding 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_modifier     mod1

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config gapless_monocle false
bspc config borderless_monocle false

pkill picom
picom --config ~/.config/picom/picom.conf &
xrandr --output DP-0 --mode 1920x1080 --rate 144.00 --primary --pos 0x0 \
       --output HDMI-0 --mode 2560x1080 --rate 74.99 --rotate right --pos 1920x0 &

# Menjalankan Polkit Authentication Agent bawaan XFCE
/usr/lib/xfce4/auth/xfce-polkit &


~/.config/polybar/launch.sh &
[ -f ~/.fehbg ] && sh ~/.fehbg &
~/.local/bin/border_focus.sh &


