[module/ewmh]
type = internal/xworkspaces

pin-workspaces = false

format = <label-state>

; Aktif → Pacman 󰮯 (md-pac_man)
label-active = %{T4}󰮯%{T-}
label-active-foreground = ${colors.yellow}
label-active-padding = 1

; Ada window (tidak aktif) → Ghost 󰊠 (md-ghost)
label-occupied = %{T4}󰊠%{T-}
label-occupied-foreground = ${colors.cyan}
label-occupied-padding = 1

; Urgent → Ghost 󰊠 merah
label-urgent = %{T4}󰊠%{T-}
label-urgent-foreground = ${colors.red}
label-urgent-padding = 1

; Kosong → Ghost 󰊠 redup
label-empty = %{T4}󰊠%{T-}
label-empty-foreground = #665c54
label-empty-padding = 1
